#include "string"
#include "iostream"
#include "lancaster.h"
#include "similarity.h"
#include "vector"
#include "algorithm"
#include "regex"

std::vector<std::string> sentence_token(const std::string& s) {
  std::vector<std::string> tokens;
  std::string token;

  std::regex rgx("[^a-zA-Z']");
  std::sregex_token_iterator iter(s.begin(),
    s.end(),
    rgx,
    -1);
  std::sregex_token_iterator end;
  for ( ; iter != end; ++iter) {
    token = *iter;
    if (token.length() == 0) continue;
    std::transform(token.begin(), token.end(), token.begin(), ::tolower);
    tokens.push_back(token);
  }
  return tokens;
}

typedef struct
{
  std::string sentence;
  std::vector<std::string> components;

} sentence_components;

class Cluster
{
public:
  Cluster(std::vector<std::string> docs, const float threshold = 0.85, const bool shuffle = true);

  // private:
  std::vector<sentence_components> stemmed_docs;
  std::map<std::string, std::map<std::string, float>> similarity_context;
};

Cluster::Cluster(std::vector<std::string> docs, const float threshold, const bool shuffle)
{
  std::transform(docs.begin(), docs.end(), std::back_inserter(this->stemmed_docs), [](std::string d) {
    std::vector<std::string> tokens = sentence_token(d);
    std::string s;
    for(std::string token: tokens) {
      std::string stemmed = lancaster_stemmer(token);
      s.append(stemmed);
    }
    return sentence_components{d, char_gram(s, 3)};
  });
}

int main()
{
  std::vector<std::string> documents{
      "He waited for the stop sign to turn to a go sign.",
      "He looked behind the door and didn't like what he saw.",
      "If I don’t like something, I’ll stay away from it.",
      "25 years later, she still regretted that specific moment.",
      "The clock within this blog and the clock on my laptop are 1 hour different from each other.",
      "The fish listened intently to what the frogs had to say.",
      "I really want to go to work, but I am too sick to drive.",
      "It didn't take long for Gary to detect the robbers were amateurs.",
      "The random sentence generator generated a random sentence about a random sentence.",
      "Joe made the sugar cookies; Susan decorated them.",
      "hE wAITED fOr tHE StoP sigN To TUrn To a go sIgN.",
      "hE LOoKEd beHiNd the DOOR aNd DIdn'T LIKE WHaT hE saW.",
      "iF I dOn’T liKe SoMeThIng, I’LL STaY AwAY froM it.",
      "25 yEaRs LaTer, SHe sTILl rEgretTed That sPECiFIC MOmENT.",
      "The CLoCK wITHin thIs BLoG aNd THe cLOck oN my LAPTOP ARe 1 HOur dIFFerEnt FROm EaCH othER.",
      "the FiSH LISTEnEd inteNtLY to whaT the froGs had to saY.",
      "i REally WanT TO gO to woRK, bUt i aM ToO sICK To DRive.",
      "IT Didn't tAkE loNG FOR garY TO Detect ThE rObBERs WeRE AMaTEuRs.",
      "tHe RaNdOm SenTeNcE gENeRatoR gENeraTed A RAnDom SEntEnCe aBOUT a rANDom SeNteNce.",
      "joE maDe THE sUgAr cOOKieS; susAn DecOrAtEd thEM.",
      "He waited until the stop sign turned into a go sign.",
      "He investigated behind the door and hated what he saw.",
      "I’ll not go near a thing if I don’t like it.",
      "She still feel unhappy about that specific moment 25 years later.",
      "The difference of the clock within this blog and the clock on my laptop is 1 hour from each other.",
      "The fish listened while giving a full attention to what the frogs had to say.",
      "I am too sick to drive even though I really want to go to work.",
      "Gary took a short time detect that the robbers were amateurs.",
      "A random sentence about a random sentence can be generated by the random sentence.",
      "Susan decorated the sugar cookies the Joe made.",
      "He waited for the cessation sign to turn to a go sign.",
      "He looked abaft the door and didn't relish what he optically discerned.",
      "If I don’t prefer something, I’ll avoid it.",
      "25 years later, she still regretted that categorical moment.",
      "This blog has a clock that has an hour difference with my laptop clock",
      "The fish heedfully aurally perceived to what the frogs had to verbalize.",
      "I authentically want to go to work, but I am feeling too unwell to drive.",
      "It took momentarily for Gary to ascertain the larcenists were tyros.",
      "The arbitrary sentence generator engendered an arbitrary sentence about an arbitrary sentence.",
      "Joe crafted the sugar cookies; Susan embellished them.",
      "Lets all be unique together until we realise we are all the same.",
      "The virus had powers none of us knew existed.",
      "Choosing to do nothing is still a choice, after all.",
      "Beach-combing replaced wine tasting as his new obsession.",
      "There should have been a time and a place, but this wasn't it.",
      "For oil spots on the floor, nothing beats parking a motorbike in the lounge.",
      "They throw cabbage that turns your brain into emotional baggage.",
      "It didn't make sense unless you had the power to eat colors.",
      "Whenever he saw a red flag warning at the beach he grabbed his surfboard."};
  
  Cluster cluster(documents);

  for(sentence_components comps: cluster.stemmed_docs) {
    std::cout << comps.sentence << ":" << std::endl;
    for(std::string gram: comps.components) {
      std::cout << "  [" << gram << "] ";
    }
    std::cout << std::endl;
  }
}
